name: first workflow
on: workflow_dispach
jobs
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo "hello world!"
      - name: print goodbye
        run: echo "done - bye!"
